version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: harun
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: ornekdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8082:8080"

volumes:
  pgdata:
