security:
    password_hashers:
        App\Entity\User:
            algorithm: auto




    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|image|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home

            logout: # Çıkış yapma yapılandırması
                path: app_logout # Kullanıcının çıkış yapacağı URL yolu (route adı)
                target: app_home  # Çıkış yaptıktan sonra yönlendirilecek URL yolu (route adı)
                # invalidate_session: true # Oturumu geçersiz kıl. Varsayılan olarak true'dur.
