# config/routes.yaml

app_controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|tr
    defaults:
        _locale: '%kernel.default_locale%'

_import_extra_routes:
    resource: './routes/'
    type: directory
